version: "3.9"
services:

  pravega:
    image: "pravega/pravega:0.9.1"
    ports:
      - "9090:9090"
      - "12345:12345"
    environment:
      - HOST_IP=pravega
    command: "standalone"

  logstash:
    build: ./logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    links:
      - pravega
    depends_on:
      - pravega

  input:
    image: elastic/filebeat:7.13.4
    volumes:
      - "../55682/:/opt/data:ro"
      - "./logstash/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
    links:
      - logstash
    depends_on:
      - logstash

  jobmanager:
    build:
      context: "./flink"
      args:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./flink_job:/opt/flink_job
      - ./cached:/opt/cached
    depends_on:
      - input

  taskmanager:
    build:
      context: "./flink"
      args:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
