version: "3.9"
services:

  pravega:
    image: "pravega/pravega:0.9.1"
    ports:
      - "9090:9090"
      - "12345:12345"
    environment:
      - HOST_IP=pravega
    command: "standalone"

  logstash:
    build: ./logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    links:
      - pravega
    depends_on:
      - pravega

  input:
    image: elastic/filebeat:7.13.4
    volumes:
      - "./log-data/55682/:/opt/data/55682:ro"
      - "./log-data/197812/:/opt/data/197812:ro"
      - "./logstash/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
    links:
      - logstash
    depends_on:
      - logstash

  jobmanager:
    build:
      context: "./flink"
      args:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./flink_job:/opt/flink/job
      - ./cached:/opt/cached
    depends_on:
      - input
      - mysql
    links:
      - mysql

  taskmanager:
    build:
      context: "./flink"
      args:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.framework.off-heap.size: 256mb
  mysql:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./log-data/55682-data.csv:/opt/55682-data.csv:ro
      - ./log-data/197812-data.csv:/opt/197812-data.csv:ro
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./mysql/privileges.sql:/docker-entrypoint-initdb.d/privileges.sql:ro

  # influxDB:
  #   image: docker.io/influxdb:1.7.11
  #   ports:
  #     - 8083:8083
  #     - 8086:8086
  #   restart: always
  #   environment:
  #     INFLUXDB_DB: demo
  #     INFLUXDB_HOST: influxdb
  #     INFLUXDB_PASSWORD: root
  #     INFLUXDB_USERNAME: root
  grafana:
    image: docker.io/grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./Visualization/grafana-dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
      - ./Visualization/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ./Visualization/dashboard-mysql.json:/var/lib/grafana/dashboards/dashboard-mysql.json
      # - ./Visualization/dashboard-influxdb.json:/var/lib/grafana/dashboards/dashboard-influxdb.json
      - ./Visualization/dashboard-sdkci.json:/var/lib/grafana/dashboards/dashboard-sdkci.json
    links:
      - mysql
    depends_on:
      - mysql