{
 "title": "SDK_CI_Dashboard",
 "time": { "from": "2021-08-15T11:25:31.610Z", "to": "2021-08-15T17:33:48.318Z" },
 "panels": [
  {
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() AS time,\nbuildresult AS metric,\ncount(task_id) AS value\nFROM Task\nwhere $__timeFilter(buildstart)\nGROUP BY 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Defects by SDK Category",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  category,\n  count(task_id) as \"Fail\"\nFROM Task\nwhere buildresult = \"Fail\" AND $__timeFilter(buildstart)\ngroup by 1\norder by 1\n\n"
    },
    {
     "rawSql": "SELECT\n  category,\n  count(task_id) as \"Warning\"\nFROM Task\nwhere buildresult = \"Warning\" AND $__timeFilter(buildstart)\ngroup by 1\norder by 1\n"
    }
   ]
  },
  {
   "title": "Defects by Platform",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  platform,\n  count(buildresult) AS \"Fail\"\nFROM Task\nWHERE\n  $__timeFilter(buildstart) AND buildresult = \"Fail\"\nGROUP BY platform"
    },
    {
     "rawSql": "SELECT\n  platform,\n  count(buildresult) AS \"Warning\"\nFROM Task\nWHERE\n  $__timeFilter(buildstart) AND buildresult = \"Warning\"\nGROUP BY platform"
    }
   ]
  },
  {
   "title": "Detected Defects",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DISTINCT(short_description) AS \"Defects\",\r\n  count(message) AS \"Count\"\r\nFROM keyErrorLog AS t1\r\nINNER JOIN (SELECT task_id, MAX(rate) FROM keyErrorLog GROUP by task_id) AS child ON (t1.task_id = child.task_id)\r\nwhere $__unixEpochFilter(task_hash/1000)\r\nGROUP BY 1\r\norder BY Count desc\r\n\r\n"
    }
   ]
  },
  {
   "title": "Build Progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(buildstart,\"1m\", 0),\n  count(task_id) AS \"building_taks\"\nFROM Task\nWHERE\n  $__timeFilter(buildstart)\nGROUP BY 1\nORDER BY $__timeGroup(buildstart,\"1m\", 0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(buildstart,\"1m\", 0),\n  count(task_id) AS \"defects\"\nFROM Task\nWHERE\n  $__timeFilter(buildstart) AND buildresult != \"Pass\"\nGROUP BY 1\nORDER BY $__timeGroup(buildstart,\"1m\", 0)"
    }
   ]
  },
  {
   "title": "Build Time Line by Toolchain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(buildstart,'5m', 0) AS \"time\",\n  compiler AS \"metric\",\n  count(task_id) AS \"value\"\nFROM Task\nwhere  $__timeFilter(buildstart)\nGROUP BY 1, metric\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Details List",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  testcase,\n  platform,\n  compiler,\n  target,\n  buildresult,\n  keyErrorLog.message as \"error\"\nFROM Task\nINNER JOIN keyErrorLog ON keyErrorLog.task_id = Task.task_id\nwhere buildresult != \"Pass\" AND $__timeFilter(buildstart)\n\n\n"
    }
   ]
  },
  {
   "title": "Average Build Duration",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  compiler,\n  avg(buildduration) AS \"buildduration\"\nFROM Task\nWHERE\n  $__timeFilter(buildstart)\nGROUP BY compiler\norder by buildduration"
    }
   ]
  }
 ]
}