FROM mysql:8.0.19

ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
ENV MYSQL_ROOT_PASSWORD=root

# ADD mysql.cnf /etc/mysql/mysql.conf.d/my.cnf
# RUN chmod 644 /etc/mysql/mysql.conf.d/my.cnf

# COPY setup.sh /mysql/setup.sh
# COPY schema.sql /mysql/schema.sql
# COPY privileges.sql /mysql/privileges.sql

# RUN ls -R /mysql

# run sh /mysql/setup.sh